### ISSUE TITLE
site seems to be not working

### ISSUE THREAD

**Issue by 678GUY** [Bartvelp/pushme#19]
Pressing the get code button does trigger the browser to ask if to allow notifications but it then just gets stuck and never gives a code, i tried on multiple browsers and both on my pc and android device and its the same in all of them

**Comment by Bartvelp** [comment]
That's weird, I can't reproduce that. I can verify the code still works on desktop and mobile firefox and desktop and mobile chrome. Please add more info about your environment. Maybe Safari isn't working? Also check your developer console for any errors.

**Comment by KaiKai7** [comment]
Does the Arduino Sketch still work ?. I can't get it to send a successful notification with a Wemos d1 mini

**Comment by Bartvelp** [comment]
Yes should still work. All it does is send a HTTPS request to a pushme URL with a JSON payload. If it doesn't work, first try to send a http request to something you know works

**Comment by KaiKai7** [comment]
> Yes should still work. All it does is send a HTTPS request to a pushme URL with a JSON payload. If it doesn't work, first try to send a http request to something you know works

Ok, cool because this is what I need. Not sure why it's not working for me though. I put a wifi connection in the sketch and it does connect and I get an IP. Seems like it is trying to send a message before fully ready

**Comment by KaiKai7** [comment]
> > Yes should still work. All it does is send a HTTPS request to a pushme URL with a JSON payload. If it doesn't work, first try to send a http request to something you know works
> 
> Ok, cool because this is what I need. Not sure why it's not working for me though. I put a wifi connection in the sketch and it does connect and I get an IP. Seems like it is trying to send a message before fully ready 

Nm, the problem was between the seat and the keyboard, lol. Got it working with Wifi Manager too. Now to also get the PushMe code to be entered through the browser and I am set. Thank you for this.

**Comment by KaiKai7** [comment]
This is not an issue with PushMe which is working great with my project.
My issue is with Chrome notifications not working after the phone is locked. Pixel 6a, I disable battery optimizations and set to show sensitive information on lockscreen hoping that was it - it was not.
It does work for a minute or two but then only delivers the notifications once the screen is unlocked.
Is there a work around for non rooted users ?.
Man, I don't want to throw this away it is exactly what I needed.

**Comment by stefunkk** [comment]
Is project dead?

![image](https://github.com/Bartvelp/pushme/assets/73523165/328a3759-6f5f-4574-9e49-a03493b3bb2e)

**Comment by MikevanBreePXL** [comment]
Error when allowing notification access:
Browser: Brave (Chromium-based)

```js
vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'postMessage')
    at Home.vue:240:40
    at new Promise (<anonymous>)
    at j (Home.vue:226:10)
    at a.<anonymous> (Home.vue:177:1)
    at u (runtime.js:45:40)
    at Generator._invoke (runtime.js:271:22)
    at forEach.t.<computed> [as next] (runtime.js:97:21)
    at i (asyncToGenerator.js:5:20)
    at c (asyncToGenerator.js:27:9)
```

**Comment by stefunkk** [comment]
> Error when allowing notification access: Browser: Brave (Chromium-based)
> 
> ```js
> vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'postMessage')
>     at Home.vue:240:40
>     at new Promise (<anonymous>)
>     at j (Home.vue:226:10)
>     at a.<anonymous> (Home.vue:177:1)
>     at u (runtime.js:45:40)
>     at Generator._invoke (runtime.js:271:22)
>     at forEach.t.<computed> [as next] (runtime.js:97:21)
>     at i (asyncToGenerator.js:5:20)
>     at c (asyncToGenerator.js:27:9)
> ```

Project is dead, you need to find new solution ;)

**Comment by Bartvelp** [comment]
Project is not strictly "dead". I am still using it daily for my own purposes. If it would fail for me I would push a fix, but I unfortunately do not have the spare time to look into other issues.
Feel free to open a pull request and I will take a look.
FYI I am using android chrome and it has worked for >4 years without changes
